@host=http://localhost:5180
@id=E9BF7B7A-C363-40E4-83B4-341ADA0CA906
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMjZlZGVkNS02YzkyLTRmNzgtYWQ0Yi04MzI1MjIyZjI2ZWIiLCJnaXZlbl9uYW1lIjoiQW50aG9ueSIsImZhbWlseV9uYW1lIjoiRGV2aWxsZSIsImp0aSI6IjRiODE5ODU3LTg4MWEtNDNiYS1hMTFjLWY0OGU4NWJlNzMzNiIsIkFkbWluIjoiZmFsc2UiLCJleHAiOjE2OTczNjc1OTgsImlzcyI6IlNjaG9vbE1hbmFnZW1lbnQiLCJhdWQiOiJTY2hvb2xNYW5hZ2VtZW50In0.VnJ6wQMA8ORXg6DcRH7eDrHV-qmBEIE0Xy9WNPZvOvI

DELETE {{host}}/schools/{{id}}
Authorization: Bearer {{token}}

