@host=http://localhost:5180
@id=979BABEB-4E81-4CA9-B6A1-471253EF1C26
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYzRmMzk1MS04NWYwLTQ5YzMtODRjOC0yNWYyMjFhNzYzZDQiLCJnaXZlbl9uYW1lIjoiQW50aG9ueSIsImZhbWlseV9uYW1lIjoiRGV2aWxsZSIsImp0aSI6IjkwOTI0OWRmLTcyYmEtNDg0Ny1hNDYyLTBmOTM2ZWU5MzQ4MiIsImV4cCI6MTY5NzM2NTM5MiwiaXNzIjoiU2Nob29sTWFuYWdlbWVudCIsImF1ZCI6IlNjaG9vbE1hbmFnZW1lbnQifQ.ndPUz7IVosbsqcUKSbvhHP3L7_IEws_kdtGxZGhi980


PUT {{host}}/schools/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "Name": "De Nayer V1",
    "SchoolType": "University"
}
